source 'https://cdn.cocoapods.org/'

platform :ios, '13'

target 'SampleApp' do
  use_modular_headers!
  use_frameworks!
  pod 'ComplyCubeMobileSDK', '2.1.0'
  
  target 'SampleAppTests' do
    inherit! :search_paths
  end

  target 'SampleAppUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      # The precompiled SDK links Swift pods and requires their public symbols at runtime.
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
