# Uncomment the next line to define a global platform for your project
plugin 'cocoapods-art', :sources => [
  'cc-cocoapods-release-local',
  'trunk'
]

platform :ios, '13'

target 'SampleApp' do
use_modular_headers!
  use_frameworks!

  # Pods for ComplyCube sample App
  pod 'ComplyCube'
  
  target 'SampleAppAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleAppUITests' do
    # Pods for testing
  end

end
